name: scarlet_app
description: Scarlet - Tactical Fire Response Application
publish_to: 'none'
version: 0.2.0

environment:
  sdk: '>=3.12.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management & DI
  flutter_riverpod: ^2.6.1

  # Networking
  dio: ^5.7.0

  # Routing
  go_router: ^14.8.1

  # Maps
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # Secure Storage
  flutter_secure_storage: ^9.2.4

  # Location
  geolocator: ^11.0.0
  permission_handler: ^11.0.1

  # Routing
  sqflite: ^2.4.0
  path_provider: ^2.1.0
  path: ^1.9.0

  # P2P & Safety
  sensors_plus: ^7.0.0
  nearby_connections: ^4.3.0
  audioplayers: ^6.0.0

  # Biometric
  local_auth: ^2.3.0
  local_auth_android: ^1.0.34

  # Utilities
  intl: ^0.20.2
  dio_http2_adapter: ^2.6.0
  flutter_dotenv: ^5.1.0
  home_widget: ^0.9.3
  grpc: ^5.1.0
  protobuf: ^6.0.0
  fixnum: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/img/logos/
    - assets/img/icons/
    - .env
    - assets/graphs/
