name: scarlet_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.14.0
  connectrpc: ^0.3.0
  protobuf: ^3.1.0
  ffi: ^2.1.4
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  # flutter_local_notifications: ^17.1.2
  flutter_localizations:
    sdk: flutter
  geolocator: ^11.0.0
  google_maps_flutter: ^2.5.3
  http: ^1.2.0
  intl: ^0.20.2
  json_serializable: ^6.7.1
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.3
  win32: ^5.11.0
  grpc: ^4.0.4
  fixnum: ^1.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/img/logos/
    - assets/img/icons/
